In [1]:
import pandas as pd
import numpy as np
import statistics as stat

# **Assignment on Statistics**

In [2]:
data = pd.read_csv('/content/Students_Performance.csv')
data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group C,some high school,free/reduced,none,0,17,10
1,female,group B,high school,free/reduced,none,8,24,23
2,female,group B,some high school,free/reduced,none,18,32,28
3,female,group B,some college,standard,none,11,38,32
4,female,group C,some college,free/reduced,none,22,39,33

**1.An Institution wishes to find out their student’s ability in mathematics, reading and writing skills. The Institution wants to do an exploratory study to check the following information.**

In [6]:
#a.Find out how many males and females participated in the test.

gender_counts = data['gender'].value_counts()

print("Number of males:", gender_counts['male'])
print("Number of females:", gender_counts['female'])

Number of males: 482
Number of females: 518

In [16]:
#b.What do you think about the students' parental level of education?

import matplotlib.pyplot as plt
parental_level_of_education = data['parental level of education'].value_counts()
parental_level_of_education

some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: parental level of education, dtype: int64

In [28]:
#c.Who scores the most on average for math, reading and writing based on
#!.Gender
#!!.Test preparation course

gender_avg_scores = data.groupby('gender').mean()
prep_course_avg_scores = data.groupby('test preparation course').mean()
print("Average scores based on gender:\n", gender_avg_scores)
print("\nAverage scores based on test preparation course:\n", prep_course_avg_scores)

Average scores based on gender:
         math score  reading score  writing score
gender
female   63.376448      72.590734      72.467181
male     68.821577      65.545643      63.446058

Average scores based on test preparation course:
                          math score  reading score  writing score
test preparation course
completed                  69.96648      74.175978      74.684358
none                       63.78972      66.417445      64.457944

<ipython-input-28-94a18633f57e>:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  gender_avg_scores = data.groupby('gender').mean()
<ipython-input-28-94a18633f57e>:6: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  prep_course_avg_scores = data.groupby('test preparation course').mean()

In [32]:
#d.What do you think about the scoring variation for math, reading and writing based on
#!.Gender
#!!.Test preparation course

gender_std_scores = data.groupby('gender').std()

prep_course_std_scores = data.groupby('test preparation course').std()

print("Standard deviation of scores based on gender:\n", gender_std_scores)
print("\nStandard deviation of scores based on test preparation course:\n", prep_course_std_scores)

Standard deviation of scores based on gender:
         math score  reading score  writing score
gender
female   16.029928      14.411018      14.844842
male     14.556411      14.149594      14.227225

Standard deviation of scores based on test preparation course:
                          math score  reading score  writing score
test preparation course
completed                 14.521847      13.537572      13.236412
none                      15.705689      14.608896      15.041667

<ipython-input-32-51337323761e>:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  gender_std_scores = data.groupby('gender').std()
<ipython-input-32-51337323761e>:7: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  prep_course_std_scores = data.groupby('test preparation course').std()

In [45]:
#e.The management needs your help to give bonus points to the top 25% of students based on their math score,
#so how will you help the management to achieve this.

sorted_data = data.sort_values(by='math score', ascending=False)
top_25_percent = int(len(data) * 0.25)
bonus_points = 10  # Adjust bonus points as needed
top_students = sorted_data.head(top_25_percent)
top_students['bonus_points'] = bonus_points

print("Top 25% of students with bonus points:\n", top_students)

Top 25% of students with bonus points:
      gender race/ethnicity parental level of education     lunch  \
999    male        group E           bachelor's degree  standard
515  female        group E                some college  standard
517  female        group E          associate's degree  standard
516  female        group E           bachelor's degree  standard
997    male        group D                some college  standard
..      ...            ...                         ...       ...
418  female        group B                 high school  standard
420  female        group C           bachelor's degree  standard
425  female        group D             master's degree  standard
429  female        group E            some high school  standard
419  female        group C           bachelor's degree  standard

    test preparation course  math score  reading score  writing score  \
999               completed         100            100            100
515                    none         100             92             97
517                    none         100            100            100
516                    none         100            100            100
997               completed         100             97             99
..                      ...         ...            ...            ...
418               completed          77             82             89
420               completed          77             94             95
425               completed          77             82             91
429                    none          77             79             80
419                    none          77             88             87

     bonus_points
999            10
515            10
517            10
516            10
997            10
..            ...
418            10
420            10
425            10
429            10
419            10

[250 rows x 9 columns]

<ipython-input-45-95019f826178>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_students['bonus_points'] = bonus_points

# **Case Study on Testing of Hypothesis**

**2.A company started to invest in digital marketing as a new way of their product promotions. For that they collected data and decided to carry out a study on it.**

In [46]:
data2 = pd.read_csv('/content/Sales_add.csv')
data2.head()

,Month,Region,Manager,Sales_before_digital_add(in $),Sales_After_digital_add(in $)
0,Month-1,Region - A,Manager - A,132921,270390
1,Month-2,Region - A,Manager - C,149559,223334
2,Month-3,Region - B,Manager - A,146278,244243
3,Month-4,Region - B,Manager - B,152167,231808
4,Month-5,Region - C,Manager - B,159525,258402

In [53]:
#a.The company wishes to clarify whether there is any increase in sales after stepping into digital marketing.

from scipy.stats import ttest_rel
t_statistic, p_value = ttest_rel(data2['Sales_before_digital_add(in $)'], data2['Sales_After_digital_add(in $)'])
alpha = 0.05

if p_value < alpha:
    print("There is a significant increase in sales after implementing digital marketing (reject the null hypothesis).")
else:
    print("There is no significant increase in sales after implementing digital marketing (fail to reject the null hypothesis).")

There is a significant increase in sales after implementing digital marketing (reject the null hypothesis).

In [61]:
#b.The company needs to check whether there is any dependency between the features “Region” and “Manager”.

from scipy.stats import chi2_contingency
contingency_table = pd.crosstab(data2['Region'], data2['Manager'])
chi2, p_value, _, _ = chi2_contingency(contingency_table)
alpha = 0.05
if p_value < alpha:
    print("There is a significant dependency between 'Region' and 'Manager' (reject the null hypothesis).")
else:
    print("There is no significant dependency between 'Region' and 'Manager' (fail to reject the null hypothesis).")

There is no significant dependency between 'Region' and 'Manager' (fail to reject the null hypothesis).